# Generated by Django 3.2.7 on 2023-06-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Имя клиента')),
                ('email', models.EmailField(max_length=254, verbose_name='Ваш емаил')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Имя проекта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Фотка')),
                ('is_aproved', models.BooleanField(default=False, verbose_name='Отображать на сайте или нет')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
